spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wdf?useUnicode=true&characterEncoding=utf-8
    username: wdf
    password: wdf
    dbcp2:
      initial-size: 0
      max-total: 10
      max-idle: 10
      min-idle: 0

logging:
  config: classpath:log4j2-dev.xml
