spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wdf?useUnicode=true&characterEncoding=utf-8
    username: wdf
    password: wdf
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        max-wait: 200ms
    timeout: 200ms

logging:
  config: classpath:log4j2-dev.xml
