spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wdf?useUnicode=true&characterEncoding=utf-8
    username: wdf
    password: wdf
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30

logging:
  config: classpath:log4j2-prod.xml
